import Box from "@mui/material/Box";
import { HorizontalCenter, MainContainer, Progress } from "components";
import Head from "next/head";
import React from "react";
import { Header } from "views/Header";
import { SideDrawer } from "views/SideDrawer";

type BasicPageProps = React.FC<{
  title?: string;
  metaDescription?: string;
  children?: React.ReactNode;
  suspense?: boolean;
}>;

export const BasicPage: BasicPageProps = ({
  title,
  metaDescription = "Generated by create next app",
  children,
  suspense = true,
}) => {
  let pageTitle = "yuchi forum";
  if (title) pageTitle = `${title} | yuchi forum`;

  return (
    <Box>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content={metaDescription} />
        <meta property="og:site_name" content="yuchi-forum" />
        <meta property="og:title" content="yuchi forum" />
        <meta property="og:description" content="廢文製造機" />
        <meta
          property="og:image"
          content="https://yuchi-forum-demo.netlify.app/yuchi-forum-logo.svg"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainContainer component="main">
        <Header />
        <HorizontalCenter alignItems="start">
          {suspense ? (
            <React.Suspense fallback={<Progress />}>{children}</React.Suspense>
          ) : (
            <>{children}</>
          )}
        </HorizontalCenter>
      </MainContainer>

      <footer></footer>
      <SideDrawer />
    </Box>
  );
};
