import Box from "@mui/material/Box";
import {
  ArticleCard,
  HorizontalCenter,
  MainContainer,
  Progress,
  SidebarContainer,
  VerticalCenter,
} from "components";
import type { NextPage } from "next";
import Head from "next/head";
import { useListPostQuery } from "store/post";
import { Header } from "views/Header";
import { HotTopic } from "views/HotTopic";
import { PostDialog } from "views/PostDialog";
import { Sidebar } from "views/Sidebar";
import { SideDrawer } from "views/SideDrawer";

const Home: NextPage = () => {
  const { data = [], isLoading } = useListPostQuery({ limit: 5 });

  return (
    <Box>
      <Head>
        <title>yuchi forum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainContainer component="main">
        <Header />
        <HorizontalCenter alignItems="start">
          <SidebarContainer>
            <Sidebar />
          </SidebarContainer>
          <VerticalCenter spacing={2}>
            {isLoading ? (
              <Progress />
            ) : (
              data.map(
                (v: {
                  pid: string;
                  createdat: string;
                  title: string;
                  excerpt: string;
                  like: string | number;
                  dislike: string | number;
                }) => (
                  <ArticleCard
                    key={v.pid}
                    postId={v.pid}
                    postedBy="Yuchi"
                    postTime={v.createdat}
                    title={v.title}
                    body={v.excerpt}
                    like={v.like}
                    dislike={v.dislike}
                    comment="3"
                  />
                )
              )
            )}
          </VerticalCenter>
          <HotTopic />
        </HorizontalCenter>
      </MainContainer>

      <footer></footer>
      <SideDrawer />
      <PostDialog />
    </Box>
  );
};

export default Home;
