import type { NextPage } from "next";
import Head from "next/head";
import styles from "styles/container.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>yuchi forum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}></main>

      <footer></footer>
    </div>
  );
};

export default Home;
