import Box from "@mui/material/Box";
import { MainContainer } from "components";
import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "views/Header";
import { SignInForm } from "views/SignInForm";

const SignIn: NextPage = () => {
  return (
    <Box>
      <Head>
        <title>SignIn | yuchi forum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer component="main">
        <Header />
        <SignInForm />
      </MainContainer>
    </Box>
  );
};

export default SignIn;
